// src/components/TiledBackground.tsx
import { useMemo } from "react";
import styles from "../styles/TiledBackground.module.css";

import analyticsMagnifyingGlass from "../assets/logos/analytics-magnifying-glass.svg";
import appsAdd from "../assets/logos/apps-add.svg";
import browser from "../assets/logos/browser.svg";
import codeWindow from "../assets/logos/code-window.svg";
import crmComputer from "../assets/logos/crm-computer.svg";
import globe from "../assets/logos/globe.svg";
import layoutFluid from "../assets/logos/layout-fluid.svg";
import marketplace from "../assets/logos/marketplace.svg";
import site from "../assets/logos/site.svg";
import worldwideNetwork from "../assets/logos/worldwide-network.svg";

const logos = [
  analyticsMagnifyingGlass,
  appsAdd,
  browser,
  codeWindow,
  crmComputer,
  globe,
  layoutFluid,
  marketplace,
  site,
  worldwideNetwork,
];

const COLS = 25;
const ROWS = 20;

const TiledBackground = () => {
  const cells = useMemo(
    () =>
      Array.from({ length: COLS * ROWS }, (_, i) => ({
        id: i,
        src: logos[Math.floor(Math.random() * logos.length)],
      })),
    []
  );

  return (
    <div className={styles.background}>
      <div className={styles.grid}>
        {cells.map((cell) => (
          <img key={cell.id} src={cell.src} className={styles.icon} alt="" />
        ))}
      </div>
    </div>
  );
};

export default TiledBackground;

// src/app/components/tiled-background/tiled-background.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-tiled-background',
  templateUrl: './tiled-background.component.html',
  styleUrls: ['./tiled-background.component.css'],
})
export class TiledBackgroundComponent implements OnInit {
  cells: { id: number; src: string }[] = [];

  private readonly logos = [
    'assets/logos/analytics-magnifying-glass.svg',
    'assets/logos/apps-add.svg',
    'assets/logos/browser.svg',
    'assets/logos/code-window.svg',
    'assets/logos/crm-computer.svg',
    'assets/logos/globe.svg',
    'assets/logos/layout-fluid.svg',
    'assets/logos/marketplace.svg',
    'assets/logos/site.svg',
    'assets/logos/worldwide-network.svg',
  ];

  private readonly COLS = 25;
  private readonly ROWS = 20;

  ngOnInit(): void {
    this.cells = Array.from({ length: this.COLS * this.ROWS }, (_, i) => ({
      id: i,
      src: this.logos[Math.floor(Math.random() * this.logos.length)],
    }));
  }
}

<div class="background">
  <div class="grid">
    <img *ngFor="let cell of cells" [src]="cell.src" class="icon" alt="" />
  </div>
</div>
