// src/components/Footer.tsx
import footerCSS from "../styles/Footer.module.css";

const Footer = () => (
    <footer className={footerCSS.footer}>
        <div className={footerCSS.inner}>
            <div className={footerCSS.top}>
                <div className={footerCSS.brand}>
                    <span className={footerCSS.name}>Borys Burdeinyi</span>
                    <span className={footerCSS.role}>Full-Stack Developer</span>
                </div>
                <nav className={footerCSS.nav}>
                    <a href="#home">Home</a>
                    <a href="#about">About</a>
                    <a href="#projects">Projects</a>
                    <a href="#contact">Contact</a>
                </nav>
            </div>

            <div className={footerCSS.divider} />

            <div className={footerCSS.bottom}>
                <span className={footerCSS.copy}>© 2025 Borys Burdeinyi. All rights reserved.</span>
                <div className={footerCSS.socials}>
                    <a href="https://t.me/Raikern" target="_blank" rel="noopener noreferrer" aria-label="Telegram">
                        <i className="ri-telegram-line" />
                    </a>
                    <a href="https://wa.me/380973431619" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp">
                        <i className="ri-whatsapp-line" />
                    </a>
                    <a href="mailto:borisburdeyniy@gmail.com" aria-label="Email">
                        <i className="ri-mail-line" />
                    </a>
                </div>
            </div>
        </div>
    </footer>
);

export default Footer;

// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { AppConfigService } from '../../services/app-config.service';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
})
export class FooterComponent {
  constructor(readonly config: AppConfigService) {}
}

<footer class="footer">
  <div class="inner">
    <div class="top">
      <div class="brand">
        <span class="name">Borys Burdeinyi</span>
        <span class="role">Full-Stack Developer</span>
      </div>
      <nav class="nav">
        <a href="#home">Home</a>
        <a href="#about">About</a>
        <a href="#approach">Approach</a>
        <a href="#services">Services</a>
        <a href="#projects">Projects</a>
        <a href="#contact" *ngIf="config.showContacts">Contact</a>
      </nav>
    </div>

    <div class="divider"></div>

    <div class="bottom">
      <span class="copy">© 2025 Borys Burdeinyi. All rights reserved.</span>
      <div class="socials" *ngIf="config.showContacts">
        <a [href]="'https://t.me/' + config.contacts.telegram" target="_blank" rel="noopener noreferrer" aria-label="Telegram">
          <i class="ri-telegram-line"></i>
        </a>
        <a [href]="'https://wa.me/' + config.contacts.whatsapp" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp">
          <i class="ri-whatsapp-line"></i>
        </a>
        <a [href]="'mailto:' + config.contacts.email" aria-label="Email">
          <i class="ri-mail-line"></i>
        </a>
      </div>
    </div>
  </div>
</footer>
