// src/app/components/contact/contact.component.ts
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';
import { ContactService } from '../../services/contact.service';

const SERVICES = ['Web Development', 'Mobile App', 'Backend / API', 'Consulting'];
const BUDGETS = ['Less than $5K', '$5K – $20K', 'More than $20K'];

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css'],
})
export class ContactComponent {
  readonly serviceOptions = SERVICES;
  readonly budgetOptions = BUDGETS;

  fullName = '';
  email = '';
  text = '';
  selectedService: string | null = null;
  selectedBudget: string | null = null;
  file: File | null = null;
  dragging = false;
  errors = { fullName: false, email: false, text: false };
  fileName = '';

  constructor(private contactService: ContactService) {}

  toggleService(s: string): void {
    this.selectedService = this.selectedService === s ? null : s;
  }

  toggleBudget(b: string): void {
    this.selectedBudget = this.selectedBudget === b ? null : b;
  }

  onFileChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files?.[0]) {
      this.file = input.files[0];
      this.fileName = this.file.name;
    }
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
    this.dragging = true;
  }

  onDragLeave(): void {
    this.dragging = false;
  }

  onDrop(event: DragEvent): void {
    event.preventDefault();
    this.dragging = false;
    const dropped = event.dataTransfer?.files[0];
    if (dropped) {
      this.file = dropped;
      this.fileName = dropped.name;
    }
  }

  triggerFileInput(fileInput: HTMLInputElement): void {
    fileInput.click();
  }

  async onSubmit(form: NgForm): Promise<void> {
    this.errors = {
      fullName: this.fullName.trim() === '',
      email: this.email.trim() === '',
      text: this.text.trim() === '',
    };
    if (Object.values(this.errors).includes(true)) return;

    const formData = new FormData();
    formData.append('fullName', this.fullName);
    formData.append('email', this.email);
    formData.append('text', this.text);
    if (this.selectedService) formData.append('service', this.selectedService);
    if (this.selectedBudget) formData.append('budget', this.selectedBudget);
    if (this.file) formData.append('file', this.file);

    this.contactService.sendMessage(formData).subscribe({
      next: () => this.clearForm(form),
      error: (err) => console.error(err),
    });
  }

  private clearForm(form: NgForm): void {
    this.fullName = '';
    this.email = '';
    this.text = '';
    this.selectedService = null;
    this.selectedBudget = null;
    this.file = null;
    this.fileName = '';
    form.resetForm();
  }
}

<section id="contact" class="section">
  <div class="wrapper">
    <!-- Left panel -->
    <div class="left">
      <div class="glow"></div>
      <div class="left-content">
        <h2 class="heading">Tell us about your<br />project</h2>
        <ul class="perks">
          <li><span class="check">✓</span> I will respond to you within 12 hours</li>
          <li><span class="check">✓</span> I'll sign an NDA if requested</li>
          <li><span class="check">✓</span> Access to dedicated specialist</li>
        </ul>
        <div class="email-link">
          <a href="mailto:borisburdeyniy@gmail.com">borisburdeyniy@gmail.com</a>
        </div>
        <p class="call-text">Always busy and want to book<br />an exact time to call?</p>
        <a href="https://t.me/Raikern" target="_blank" rel="noopener noreferrer" class="call-btn">
          Book a free call
        </a>
      </div>
    </div>

    <!-- Right panel -->
    <form class="right" #contactForm="ngForm" (ngSubmit)="onSubmit(contactForm)" novalidate>

      <div class="field-group">
        <span class="label">Service</span>
        <div class="chips">
          <button *ngFor="let s of serviceOptions" type="button"
                  class="chip"
                  [class.chip-active]="selectedService === s"
                  (click)="toggleService(s)">
            {{ s }}
          </button>
        </div>
      </div>

      <div class="field-group">
        <span class="label">Budget</span>
        <div class="chips">
          <button *ngFor="let b of budgetOptions" type="button"
                  class="chip"
                  [class.chip-active]="selectedBudget === b"
                  (click)="toggleBudget(b)">
            {{ b }}
          </button>
        </div>
      </div>

      <div class="row">
        <div class="input-wrap">
          <input type="text" placeholder="Full name*"
                 [(ngModel)]="fullName" name="fullName"
                 class="input" [class.input-error]="errors.fullName" />
        </div>
        <div class="input-wrap">
          <input type="email" placeholder="Email*"
                 [(ngModel)]="email" name="email"
                 class="input" [class.input-error]="errors.email" />
        </div>
      </div>

      <textarea placeholder="Project details*"
                [(ngModel)]="text" name="text"
                class="textarea" [class.input-error]="errors.text"></textarea>

      <div class="dropzone"
           [class.dropzone-active]="dragging"
           (dragover)="onDragOver($event)"
           (dragleave)="onDragLeave()"
           (drop)="onDrop($event)"
           (click)="triggerFileInput(fileInput)">
        <input #fileInput type="file" style="display: none" (change)="onFileChange($event)" />
        <span class="dropzone-label">{{ fileName || 'Attach a file (optional)' }}</span>
        <span class="dropzone-hint">{{ file ? 'Click to change' : 'Choose a file or drag and drop here' }}</span>
      </div>

      <button type="submit" class="submit-btn">Submit inquiry</button>
    </form>
  </div>
</section>

// src/components/Contact.tsx
import { useState, useRef } from "react";
import contactCSS from "../styles/Contact.module.css";
import { sendMessage } from "../http/contactAPI";

const SERVICES = ["Web Development", "Mobile App", "Backend / API", "Consulting"];
const BUDGETS = ["Less than $5K", "$5K – $20K", "More than $20K"];

const Contact = () => {
    const [fullName, setFullName] = useState("");
    const [email, setEmail] = useState("");
    const [text, setText] = useState("");
    const [service, setService] = useState<string | null>(null);
    const [budget, setBudget] = useState<string | null>(null);
    const [file, setFile] = useState<File | null>(null);
    const [dragging, setDragging] = useState(false);
    const [errors, setErrors] = useState({ fullName: false, email: false, text: false });
    const fileInputRef = useRef<HTMLInputElement>(null);

    const clearForm = () => {
        setFullName(""); setEmail(""); setText("");
        setService(null); setBudget(null); setFile(null);
    };

    const handleSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        const newErrors = {
            fullName: fullName.trim() === "",
            email: email.trim() === "",
            text: text.trim() === "",
        };
        setErrors(newErrors);
        if (Object.values(newErrors).includes(true)) return;

        const formData = new FormData();
        formData.append("fullName", fullName);
        formData.append("email", email);
        formData.append("text", text);
        if (service) formData.append("service", service);
        if (budget) formData.append("budget", budget);
        if (file) formData.append("file", file);

        await sendMessage(formData).catch(console.error);
        clearForm();
    };

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault();
        setDragging(false);
        const dropped = e.dataTransfer.files[0];
        if (dropped) setFile(dropped);
    };

    return (
        <section id="contact" className={contactCSS.section}>
            <div className={contactCSS.wrapper}>
                {/* ── Left panel ── */}
                <div className={contactCSS.left}>
                    <div className={contactCSS.glow} />
                    <div className={contactCSS.leftContent}>
                        <h2 className={contactCSS.heading}>
                            Tell us about your<br />project
                        </h2>
                        <ul className={contactCSS.perks}>
                            <li><span className={contactCSS.check}>✓</span> I will respond to you within 12 hours</li>
                            <li><span className={contactCSS.check}>✓</span> I'll sign an NDA if requested</li>
                            <li><span className={contactCSS.check}>✓</span> Access to dedicated specialist</li>
                        </ul>
                        <div className={contactCSS.emailLink}>
                            <a href="mailto:borisburdeyniy@gmail.com">borisburdeyniy@gmail.com</a>
                        </div>
                        <p className={contactCSS.callText}>
                            Always busy and want to book<br />an exact time to call?
                        </p>
                        <a
                            href="https://t.me/Raikern"
                            target="_blank"
                            rel="noopener noreferrer"
                            className={contactCSS.callBtn}
                        >
                            Book a free call
                        </a>
                    </div>
                </div>

                {/* ── Right panel ── */}
                <form className={contactCSS.right} onSubmit={handleSubmit} noValidate>
                    <div className={contactCSS.fieldGroup}>
                        <span className={contactCSS.label}>Service</span>
                        <div className={contactCSS.chips}>
                            {SERVICES.map(s => (
                                <button
                                    key={s}
                                    type="button"
                                    className={`${contactCSS.chip} ${service === s ? contactCSS.chipActive : ""}`}
                                    onClick={() => setService(s === service ? null : s)}
                                >
                                    {s}
                                </button>
                            ))}
                        </div>
                    </div>

                    <div className={contactCSS.fieldGroup}>
                        <span className={contactCSS.label}>Budget</span>
                        <div className={contactCSS.chips}>
                            {BUDGETS.map(b => (
                                <button
                                    key={b}
                                    type="button"
                                    className={`${contactCSS.chip} ${budget === b ? contactCSS.chipActive : ""}`}
                                    onClick={() => setBudget(b === budget ? null : b)}
                                >
                                    {b}
                                </button>
                            ))}
                        </div>
                    </div>

                    <div className={contactCSS.row}>
                        <div className={contactCSS.inputWrap}>
                            <input
                                type="text"
                                placeholder="Full name*"
                                value={fullName}
                                onChange={e => setFullName(e.target.value)}
                                className={`${contactCSS.input} ${errors.fullName ? contactCSS.inputError : ""}`}
                            />
                        </div>
                        <div className={contactCSS.inputWrap}>
                            <input
                                type="email"
                                placeholder="Email*"
                                value={email}
                                onChange={e => setEmail(e.target.value)}
                                className={`${contactCSS.input} ${errors.email ? contactCSS.inputError : ""}`}
                            />
                        </div>
                    </div>

                    <textarea
                        placeholder="Project details*"
                        value={text}
                        onChange={e => setText(e.target.value)}
                        className={`${contactCSS.textarea} ${errors.text ? contactCSS.inputError : ""}`}
                    />

                    <div
                        className={`${contactCSS.dropzone} ${dragging ? contactCSS.dropzoneActive : ""}`}
                        onDragOver={e => { e.preventDefault(); setDragging(true); }}
                        onDragLeave={() => setDragging(false)}
                        onDrop={handleDrop}
                        onClick={() => fileInputRef.current?.click()}
                    >
                        <input
                            ref={fileInputRef}
                            type="file"
                            style={{ display: "none" }}
                            onChange={e => setFile(e.target.files?.[0] ?? null)}
                        />
                        <span className={contactCSS.dropzoneLabel}>
                            {file ? file.name : "Attach a file (optional)"}
                        </span>
                        <span className={contactCSS.dropzoneHint}>
                            {file ? "Click to change" : "Choose a file or drag and drop here"}
                        </span>
                    </div>

                    <button type="submit" className={contactCSS.submitBtn}>
                        Submit inquiry
                    </button>
                </form>
            </div>
        </section>
    );
};

export default Contact;
